<a href="https://colab.research.google.com/github/SeongwonTak/-KDT-_AI_2_Notes/blob/main/Linalg/0426_Linear_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Systems with Numpy

$Ax = b$ 문제의 해결 및 Numpy를 사용한 풀이법에 대해 알아보자.


In [1]:
import numpy as np

In [3]:
# 행렬 표현
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [5]:
# 상수항
b = np.array([4, 1, 2])

In [6]:
# 역행렬
A_inv = np.linalg.inv(A)

print(A_inv)

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]


In [7]:
# 역행렬 곱해서 풀기
x = A_inv @ b
print(x)

[ 1. -1.  2.]


In [10]:
# 검증
bb = A @ x
print(bb)

# 역행렬을 수치해석적으로 계산하기에 norm의 크기로 검증한다.
if np.linalg.norm(b - bb) < 1e-5:
  print("Solution is nice:)")
else:
  print("Something went worng:(")

[4. 1. 2.]
Solution is nice


Remark. np.matmul(A, B)로도 행렬 계산 가능.

In [11]:
bb1 = A @ x
bb2 = np.matmul(A, x)

print(bb1)
print(bb2)

[4. 1. 2.]
[4. 1. 2.]
