<a href="https://colab.research.google.com/github/SeongwonTak/-KDT-_AI_2_Notes/blob/main/Linalg/0503_Numpy_Note.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 

In [4]:
import numpy as np

## Matrix Indexing

In [12]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
b = a[1:3, 0:2]
print(b)

[[4 5]
 [7 8]]


## Array의 BroadCasting

In [13]:
# Example 1 M*N, 1*N의 연산
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,2,5])
a * x
# 결과가 각 행별로 적용 완료.

array([[ 0,  4, 15],
       [ 0, 10, 30],
       [ 0, 16, 45]])

In [7]:
# Example 2 M*N, M*1의 연산
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
x = np.array([0,9,99])

x = x[:, None]
print(x)
print(a + x)
# 결과가 각 행별로 적용 완료.

[[ 0]
 [ 9]
 [99]]
[[  1   2   3   4]
 [ 13  14  15  16]
 [106 107 108 109]]


In [10]:
# 주의사항
X = np.array([1, 3, 9])
X1 = X[:, None]
X2 = X.T  # 1차원이면 잘 안된다. X1처럼 해야한다.
print(X1)
print(X2)

[[1]
 [3]
 [9]]
[1 3 9]


In [15]:
# Example 3  M*1  1*N의 연산
t = np.array([1, 2, 3])
t = t[:,None] # t 전치
u = np.array([3, 2, 1])
print( t + u)

#([1,1,1],[2,2,2],[3,3,3]) + ([3,2,1]. [3,2,1], [3,2,1])

[[4 3 2]
 [5 4 3]
 [6 5 4]]


# Numpy와 선형대수

In [16]:
# Zero Vector
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# One Vector
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# diagonal_matrix 생성
np.diag((1, 2, 3, 4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
# identity_matrix 생성
# dtype을 지정 가능 (int, flot, unsigned_int, complex?)
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
# np_dot matrix
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[5, 1], [-1, 4]])
mat_1 @ mat_2
# mat_1.dot(mat_2)

array([[ 1, 17],
       [ 7, 14]])

In [27]:
# trace, det, inv
a = np.array([[1,2,3],[4,5,7],[7,8,9]])
print(a.trace())
print(np.linalg.det(a))
print(np.linalg.inv(a))

15
6.0
[[-1.83333333  1.         -0.16666667]
 [ 2.16666667 -2.          0.83333333]
 [-0.5         1.         -0.5       ]]


In [29]:
# eigen value and eigen vector
a = np.array([[1,0,1],[0,1,1],[2,1,1]])
np.linalg.eig(a)
# column이 eigenvector임에 주의하자.

(array([-0.73205081,  2.73205081,  1.        ]),
 array([[-4.47213595e-01,  4.47213595e-01,  4.47213595e-01],
        [-4.47213595e-01,  4.47213595e-01, -8.94427191e-01],
        [ 7.74596669e-01,  7.74596669e-01,  1.82289065e-17]]))

In [30]:
# validation of eigen_vector
eig_val, eig_vec = np.linalg.eig(a)
a @ eig_vec[:, 0]

array([ 0.32738307,  0.32738307, -0.56704412])

In [31]:
eig_val[0] * eig_vec[:, 0]

array([ 0.32738307,  0.32738307, -0.56704412])